### ISSUE TITLE
Înregistrarea în sistem prin intermediul botului

### ISSUE THREAD

**Issue by ralienpp** [code4moldova/covid19md-voluntari-tg-client#16]
Avem nevoie de comanda `/vreausaajut`? (la moment nu face nimic, https://github.com/code4moldova/covid19md-voluntari-tg-client/blob/a158416c34f27a879fe564ef7c9c68ffabaa2f84/main.py#L91)

Ideea este că cineva poate să-și instaleze botul și să se înregistreze în sistem prin Telegram (nu prin pagina web și nu telefonic, prin dialog cu operatorul sau fixerul).

Acest mecanism nu exclude fixerul din procesul de luare a deciziei, dar permite voluntarului să transmită proactiv toată informația despre sine (phone#, name, etc.), iar la fixer va apărea o alertă care spune că omul cutare vrea să fie voluntar, iar toate câmpurile formularului vor fi pre-completate.

**Comment by johnsmithm** [comment]
idea este foarte buna, informatia poate fi transmisa spre server si setat proprietatea `is_active` to `false` pana un fixer verifica. Adauga automat chat-id in db, si face legatura telegram si voluntar.

**Comment by ralienpp** [comment]
- [ ] Poți adăuga aici o mostră de JSON, pe care botul trebuie s-o trimită spre backend
- [x] URL spre care trebuie să se ducă acest request

**Comment by alexciornii** [comment]
POST <backend>/api/volunteer

**Comment by alexciornii** [comment]
```
{
    "first_name" : "newuser",
    "last_name" : "newuser",
    "email" : "newuser@mail.ru",
 ? "password" : "password123123123",
    "phone" : "12345678",
    "telegram_id" : "username",
    "telegram_chat_id" : "12345978"
 ? "telegram_secret" : "secret",
    "address" : "str. Adress",
 ? "zone_address" : "zone",
 ? "facebook_profile" : "link to profile",
    "age" : "99",
 ? "availability" : "id of type of availability(d2h per daay, 4 hour/week etc)",
 ? "activity_types" : ["activity1", "activity2"],
 ? "team" : "team",
    "profession": "test",
 ? "comments": "some comment"
}
```
@johnsmithm keys cu **?** trebuie de vazut daca trebuiesc, si daca nu mai trebuie ceva de adaugat

**Comment by johnsmithm** [comment]
trebuie `availability`, in ore de la 1 la 8.
@mihaelataranu7 ce zic utilizatorii?

**Comment by mihaelataranu7** [comment]
Utilizatorii credeau inițial că va fi această funcție! Ar fi superb s-o implementăm!

**Comment by ralienpp** [comment]
Copia buletinului sau ceva similar nu trebuie de transmis? În ce mod fixerul va „filtra” voluntarii nu_buni?

Pentru a minimiza numărul de acțiuni pe care trebuie să le efectueze fixerul și voluntarul, trebuie să pregătim din start tot pachetul; ca să nu fie așa cum e în sistemul birocratic - mergi la ghișeul 2, apoi adă hârtia de la "Райсобес", apoi stai în rând la ghișeul 4, iar apoi Raisa Haralampievna îți va spune ce mai trebuie, dacă mai trebuie ceva.

Dacă tot asta se face într-o întâlnire fizică (mă refer la verificarea documentelor și eliberarea unui permis), atunci voluntarul ar trebui să primească în final o listă de documente pe care trebuie să le aducă, unde să vină, și la ce oră.


Procedura curentă de "onboarding" e documentată undeva? Analiza preliminară a acesteia este  necesară pentru implementarea adecvată a acestui feature.

**Comment by ralienpp** [comment]
Resolved in https://github.com/code4moldova/covid19md-voluntari-tg-client/pull/38
